# Define your admin routes here
app_albums_api:
    type: rest
    prefix: /admin/api
    resource: App\Controller\Admin\AlbumController
    name_prefix: app.

app_application_settings_api:
    type: rest
    prefix: /admin/api
    resource: App\Controller\Admin\ApplicationSettingsController
    name_prefix: app.
